spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imdb_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8000
